UPDATE speakers
SET
    "Region" = CASE LOWER(country)
        WHEN 'af' THEN 'Asia'
        WHEN 'ax' THEN 'Europe'
        WHEN 'al' THEN 'Europe'
        WHEN 'dz' THEN 'Africa'
        WHEN 'as' THEN 'Oceania'
        WHEN 'ad' THEN 'Europe'
        WHEN 'ao' THEN 'Africa'
        WHEN 'ai' THEN 'Americas'
        WHEN 'aq' THEN 'Unknown'
        WHEN 'ag' THEN 'Americas'
        WHEN 'ar' THEN 'Americas'
        WHEN 'am' THEN 'Asia'
        WHEN 'aw' THEN 'Americas'
        WHEN 'au' THEN 'Oceania'
        WHEN 'at' THEN 'Europe'
        WHEN 'az' THEN 'Asia'
        WHEN 'bs' THEN 'Americas'
        WHEN 'bh' THEN 'Asia'
        WHEN 'bd' THEN 'Asia'
        WHEN 'bb' THEN 'Americas'
        WHEN 'by' THEN 'Europe'
        WHEN 'be' THEN 'Europe'
        WHEN 'bz' THEN 'Americas'
        WHEN 'bj' THEN 'Africa'
        WHEN 'bm' THEN 'Americas'
        WHEN 'bt' THEN 'Asia'
        WHEN 'bo' THEN 'Americas'
        WHEN 'bq' THEN 'Americas'
        WHEN 'ba' THEN 'Europe'
        WHEN 'bw' THEN 'Africa'
        WHEN 'bv' THEN 'Americas'
        WHEN 'br' THEN 'Americas'
        WHEN 'io' THEN 'Africa'
        WHEN 'bn' THEN 'Asia'
        WHEN 'bg' THEN 'Europe'
        WHEN 'bf' THEN 'Africa'
        WHEN 'bi' THEN 'Africa'
        WHEN 'cv' THEN 'Africa'
        WHEN 'kh' THEN 'Asia'
        WHEN 'cm' THEN 'Africa'
        WHEN 'ca' THEN 'Americas'
        WHEN 'ky' THEN 'Americas'
        WHEN 'cf' THEN 'Africa'
        WHEN 'td' THEN 'Africa'
        WHEN 'cl' THEN 'Americas'
        WHEN 'cn' THEN 'Asia'
        WHEN 'cx' THEN 'Oceania'
        WHEN 'cc' THEN 'Oceania'
        WHEN 'co' THEN 'Americas'
        WHEN 'km' THEN 'Africa'
        WHEN 'cg' THEN 'Africa'
        WHEN 'cd' THEN 'Africa'
        WHEN 'ck' THEN 'Oceania'
        WHEN 'cr' THEN 'Americas'
        WHEN 'ci' THEN 'Africa'
        WHEN 'hr' THEN 'Europe'
        WHEN 'cu' THEN 'Americas'
        WHEN 'cw' THEN 'Americas'
        WHEN 'cy' THEN 'Asia'
        WHEN 'cz' THEN 'Europe'
        WHEN 'dk' THEN 'Europe'
        WHEN 'dj' THEN 'Africa'
        WHEN 'dm' THEN 'Americas'
        WHEN 'do' THEN 'Americas'
        WHEN 'ec' THEN 'Americas'
        WHEN 'eg' THEN 'Africa'
        WHEN 'sv' THEN 'Americas'
        WHEN 'gq' THEN 'Africa'
        WHEN 'er' THEN 'Africa'
        WHEN 'ee' THEN 'Europe'
        WHEN 'sz' THEN 'Africa'
        WHEN 'et' THEN 'Africa'
        WHEN 'fk' THEN 'Americas'
        WHEN 'fo' THEN 'Europe'
        WHEN 'fj' THEN 'Oceania'
        WHEN 'fi' THEN 'Europe'
        WHEN 'fr' THEN 'Europe'
        WHEN 'gf' THEN 'Americas'
        WHEN 'pf' THEN 'Oceania'
        WHEN 'tf' THEN 'Africa'
        WHEN 'ga' THEN 'Africa'
        WHEN 'gm' THEN 'Africa'
        WHEN 'ge' THEN 'Asia'
        WHEN 'de' THEN 'Europe'
        WHEN 'gh' THEN 'Africa'
        WHEN 'gi' THEN 'Europe'
        WHEN 'gr' THEN 'Europe'
        WHEN 'gl' THEN 'Americas'
        WHEN 'gd' THEN 'Americas'
        WHEN 'gp' THEN 'Americas'
        WHEN 'gu' THEN 'Oceania'
        WHEN 'gt' THEN 'Americas'
        WHEN 'gg' THEN 'Europe'
        WHEN 'gn' THEN 'Africa'
        WHEN 'gw' THEN 'Africa'
        WHEN 'gy' THEN 'Americas'
        WHEN 'ht' THEN 'Americas'
        WHEN 'hm' THEN 'Oceania'
        WHEN 'va' THEN 'Europe'
        WHEN 'hn' THEN 'Americas'
        WHEN 'hk' THEN 'Asia'
        WHEN 'hu' THEN 'Europe'
        WHEN 'is' THEN 'Europe'
        WHEN 'in' THEN 'Asia'
        WHEN 'id' THEN 'Asia'
        WHEN 'ir' THEN 'Asia'
        WHEN 'iq' THEN 'Asia'
        WHEN 'ie' THEN 'Europe'
        WHEN 'im' THEN 'Europe'
        WHEN 'il' THEN 'Asia'
        WHEN 'it' THEN 'Europe'
        WHEN 'jm' THEN 'Americas'
        WHEN 'jp' THEN 'Asia'
        WHEN 'je' THEN 'Europe'
        WHEN 'jo' THEN 'Asia'
        WHEN 'kz' THEN 'Asia'
        WHEN 'ke' THEN 'Africa'
        WHEN 'ki' THEN 'Oceania'
        WHEN 'kp' THEN 'Asia'
        WHEN 'kr' THEN 'Asia'
        WHEN 'kw' THEN 'Asia'
        WHEN 'kg' THEN 'Asia'
        WHEN 'la' THEN 'Asia'
        WHEN 'lv' THEN 'Europe'
        WHEN 'lb' THEN 'Asia'
        WHEN 'ls' THEN 'Africa'
        WHEN 'lr' THEN 'Africa'
        WHEN 'ly' THEN 'Africa'
        WHEN 'li' THEN 'Europe'
        WHEN 'lt' THEN 'Europe'
        WHEN 'lu' THEN 'Europe'
        WHEN 'mo' THEN 'Asia'
        WHEN 'mg' THEN 'Africa'
        WHEN 'mw' THEN 'Africa'
        WHEN 'my' THEN 'Asia'
        WHEN 'mv' THEN 'Asia'
        WHEN 'ml' THEN 'Africa'
        WHEN 'mt' THEN 'Europe'
        WHEN 'mh' THEN 'Oceania'
        WHEN 'mq' THEN 'Americas'
        WHEN 'mr' THEN 'Africa'
        WHEN 'mu' THEN 'Africa'
        WHEN 'yt' THEN 'Africa'
        WHEN 'mx' THEN 'Americas'
        WHEN 'fm' THEN 'Oceania'
        WHEN 'md' THEN 'Europe'
        WHEN 'mc' THEN 'Europe'
        WHEN 'mn' THEN 'Asia'
        WHEN 'me' THEN 'Europe'
        WHEN 'ms' THEN 'Americas'
        WHEN 'ma' THEN 'Africa'
        WHEN 'mz' THEN 'Africa'
        WHEN 'mm' THEN 'Asia'
        WHEN 'na' THEN 'Africa'
        WHEN 'nr' THEN 'Oceania'
        WHEN 'np' THEN 'Asia'
        WHEN 'nl' THEN 'Europe'
        WHEN 'nc' THEN 'Oceania'
        WHEN 'nz' THEN 'Oceania'
        WHEN 'ni' THEN 'Americas'
        WHEN 'ne' THEN 'Africa'
        WHEN 'ng' THEN 'Africa'
        WHEN 'nu' THEN 'Oceania'
        WHEN 'nf' THEN 'Oceania'
        WHEN 'mk' THEN 'Europe'
        WHEN 'mp' THEN 'Oceania'
        WHEN 'no' THEN 'Europe'
        WHEN 'om' THEN 'Asia'
        WHEN 'pk' THEN 'Asia'
        WHEN 'pw' THEN 'Oceania'
        WHEN 'ps' THEN 'Asia'
        WHEN 'pa' THEN 'Americas'
        WHEN 'pg' THEN 'Oceania'
        WHEN 'py' THEN 'Americas'
        WHEN 'pe' THEN 'Americas'
        WHEN 'ph' THEN 'Asia'
        WHEN 'pn' THEN 'Oceania'
        WHEN 'pl' THEN 'Europe'
        WHEN 'pt' THEN 'Europe'
        WHEN 'pr' THEN 'Americas'
        WHEN 'qa' THEN 'Asia'
        WHEN 're' THEN 'Africa'
        WHEN 'ro' THEN 'Europe'
        WHEN 'ru' THEN 'Europe'
        WHEN 'rw' THEN 'Africa'
        WHEN 'bl' THEN 'Americas'
        WHEN 'sh' THEN 'Africa'
        WHEN 'kn' THEN 'Americas'
        WHEN 'lc' THEN 'Americas'
        WHEN 'mf' THEN 'Americas'
        WHEN 'pm' THEN 'Americas'
        WHEN 'vc' THEN 'Americas'
        WHEN 'ws' THEN 'Oceania'
        WHEN 'sm' THEN 'Europe'
        WHEN 'st' THEN 'Africa'
        WHEN 'sa' THEN 'Asia'
        WHEN 'sn' THEN 'Africa'
        WHEN 'rs' THEN 'Europe'
        WHEN 'sc' THEN 'Africa'
        WHEN 'sl' THEN 'Africa'
        WHEN 'sg' THEN 'Asia'
        WHEN 'sx' THEN 'Americas'
        WHEN 'sk' THEN 'Europe'
        WHEN 'si' THEN 'Europe'
        WHEN 'sb' THEN 'Oceania'
        WHEN 'so' THEN 'Africa'
        WHEN 'za' THEN 'Africa'
        WHEN 'gs' THEN 'Americas'
        WHEN 'ss' THEN 'Africa'
        WHEN 'es' THEN 'Europe'
        WHEN 'lk' THEN 'Asia'
        WHEN 'sd' THEN 'Africa'
        WHEN 'sr' THEN 'Americas'
        WHEN 'sj' THEN 'Europe'
        WHEN 'se' THEN 'Europe'
        WHEN 'ch' THEN 'Europe'
        WHEN 'sy' THEN 'Asia'
        WHEN 'tw' THEN 'Unknown'
        WHEN 'tj' THEN 'Asia'
        WHEN 'tz' THEN 'Africa'
        WHEN 'th' THEN 'Asia'
        WHEN 'tl' THEN 'Asia'
        WHEN 'tg' THEN 'Africa'
        WHEN 'tk' THEN 'Oceania'
        WHEN 'to' THEN 'Oceania'
        WHEN 'tt' THEN 'Americas'
        WHEN 'tn' THEN 'Africa'
        WHEN 'tr' THEN 'Asia'
        WHEN 'tm' THEN 'Asia'
        WHEN 'tc' THEN 'Americas'
        WHEN 'tv' THEN 'Oceania'
        WHEN 'ug' THEN 'Africa'
        WHEN 'ua' THEN 'Europe'
        WHEN 'ae' THEN 'Asia'
        WHEN 'gb' THEN 'Europe'
        WHEN 'us' THEN 'Americas'
        WHEN 'um' THEN 'Oceania'
        WHEN 'uy' THEN 'Americas'
        WHEN 'uz' THEN 'Asia'
        WHEN 'vu' THEN 'Oceania'
        WHEN 've' THEN 'Americas'
        WHEN 'vn' THEN 'Asia'
        WHEN 'vg' THEN 'Americas'
        WHEN 'vi' THEN 'Americas'
        WHEN 'wf' THEN 'Oceania'
        WHEN 'eh' THEN 'Africa'
        WHEN 'ye' THEN 'Asia'
        WHEN 'zm' THEN 'Africa'
        WHEN 'zw' THEN 'Africa'
        ELSE 'Unknown'
    END,
    "SubRegion" = CASE LOWER(country)
        WHEN 'af' THEN 'Southern Asia'
        WHEN 'ax' THEN 'Northern Europe'
        WHEN 'al' THEN 'Southern Europe'
        WHEN 'dz' THEN 'Northern Africa'
        WHEN 'as' THEN 'Polynesia'
        WHEN 'ad' THEN 'Southern Europe'
        WHEN 'ao' THEN 'Sub-Saharan Africa'
        WHEN 'ai' THEN 'Latin America and the Caribbean'
        WHEN 'aq' THEN 'Unknown'
        WHEN 'ag' THEN 'Latin America and the Caribbean'
        WHEN 'ar' THEN 'Latin America and the Caribbean'
        WHEN 'am' THEN 'Western Asia'
        WHEN 'aw' THEN 'Latin America and the Caribbean'
        WHEN 'au' THEN 'Australia and New Zealand'
        WHEN 'at' THEN 'Western Europe'
        WHEN 'az' THEN 'Western Asia'
        WHEN 'bs' THEN 'Latin America and the Caribbean'
        WHEN 'bh' THEN 'Western Asia'
        WHEN 'bd' THEN 'Southern Asia'
        WHEN 'bb' THEN 'Latin America and the Caribbean'
        WHEN 'by' THEN 'Eastern Europe'
        WHEN 'be' THEN 'Western Europe'
        WHEN 'bz' THEN 'Latin America and the Caribbean'
        WHEN 'bj' THEN 'Sub-Saharan Africa'
        WHEN 'bm' THEN 'Northern America'
        WHEN 'bt' THEN 'Southern Asia'
        WHEN 'bo' THEN 'Latin America and the Caribbean'
        WHEN 'bq' THEN 'Latin America and the Caribbean'
        WHEN 'ba' THEN 'Southern Europe'
        WHEN 'bw' THEN 'Sub-Saharan Africa'
        WHEN 'bv' THEN 'Latin America and the Caribbean'
        WHEN 'br' THEN 'Latin America and the Caribbean'
        WHEN 'io' THEN 'Sub-Saharan Africa'
        WHEN 'bn' THEN 'South-eastern Asia'
        WHEN 'bg' THEN 'Eastern Europe'
        WHEN 'bf' THEN 'Sub-Saharan Africa'
        WHEN 'bi' THEN 'Sub-Saharan Africa'
        WHEN 'cv' THEN 'Sub-Saharan Africa'
        WHEN 'kh' THEN 'South-eastern Asia'
        WHEN 'cm' THEN 'Sub-Saharan Africa'
        WHEN 'ca' THEN 'Northern America'
        WHEN 'ky' THEN 'Latin America and the Caribbean'
        WHEN 'cf' THEN 'Sub-Saharan Africa'
        WHEN 'td' THEN 'Sub-Saharan Africa'
        WHEN 'cl' THEN 'Latin America and the Caribbean'
        WHEN 'cn' THEN 'Eastern Asia'
        WHEN 'cx' THEN 'Australia and New Zealand'
        WHEN 'cc' THEN 'Australia and New Zealand'
        WHEN 'co' THEN 'Latin America and the Caribbean'
        WHEN 'km' THEN 'Sub-Saharan Africa'
        WHEN 'cg' THEN 'Sub-Saharan Africa'
        WHEN 'cd' THEN 'Sub-Saharan Africa'
        WHEN 'ck' THEN 'Polynesia'
        WHEN 'cr' THEN 'Latin America and the Caribbean'
        WHEN 'ci' THEN 'Sub-Saharan Africa'
        WHEN 'hr' THEN 'Southern Europe'
        WHEN 'cu' THEN 'Latin America and the Caribbean'
        WHEN 'cw' THEN 'Latin America and the Caribbean'
        WHEN 'cy' THEN 'Western Asia'
        WHEN 'cz' THEN 'Eastern Europe'
        WHEN 'dk' THEN 'Northern Europe'
        WHEN 'dj' THEN 'Sub-Saharan Africa'
        WHEN 'dm' THEN 'Latin America and the Caribbean'
        WHEN 'do' THEN 'Latin America and the Caribbean'
        WHEN 'ec' THEN 'Latin America and the Caribbean'
        WHEN 'eg' THEN 'Northern Africa'
        WHEN 'sv' THEN 'Latin America and the Caribbean'
        WHEN 'gq' THEN 'Sub-Saharan Africa'
        WHEN 'er' THEN 'Sub-Saharan Africa'
        WHEN 'ee' THEN 'Northern Europe'
        WHEN 'sz' THEN 'Sub-Saharan Africa'
        WHEN 'et' THEN 'Sub-Saharan Africa'
        WHEN 'fk' THEN 'Latin America and the Caribbean'
        WHEN 'fo' THEN 'Northern Europe'
        WHEN 'fj' THEN 'Melanesia'
        WHEN 'fi' THEN 'Northern Europe'
        WHEN 'fr' THEN 'Western Europe'
        WHEN 'gf' THEN 'Latin America and the Caribbean'
        WHEN 'pf' THEN 'Polynesia'
        WHEN 'tf' THEN 'Sub-Saharan Africa'
        WHEN 'ga' THEN 'Sub-Saharan Africa'
        WHEN 'gm' THEN 'Sub-Saharan Africa'
        WHEN 'ge' THEN 'Western Asia'
        WHEN 'de' THEN 'Western Europe'
        WHEN 'gh' THEN 'Sub-Saharan Africa'
        WHEN 'gi' THEN 'Southern Europe'
        WHEN 'gr' THEN 'Southern Europe'
        WHEN 'gl' THEN 'Northern America'
        WHEN 'gd' THEN 'Latin America and the Caribbean'
        WHEN 'gp' THEN 'Latin America and the Caribbean'
        WHEN 'gu' THEN 'Micronesia'
        WHEN 'gt' THEN 'Latin America and the Caribbean'
        WHEN 'gg' THEN 'Northern Europe'
        WHEN 'gn' THEN 'Sub-Saharan Africa'
        WHEN 'gw' THEN 'Sub-Saharan Africa'
        WHEN 'gy' THEN 'Latin America and the Caribbean'
        WHEN 'ht' THEN 'Latin America and the Caribbean'
        WHEN 'hm' THEN 'Australia and New Zealand'
        WHEN 'va' THEN 'Southern Europe'
        WHEN 'hn' THEN 'Latin America and the Caribbean'
        WHEN 'hk' THEN 'Eastern Asia'
        WHEN 'hu' THEN 'Eastern Europe'
        WHEN 'is' THEN 'Northern Europe'
        WHEN 'in' THEN 'Southern Asia'
        WHEN 'id' THEN 'South-eastern Asia'
        WHEN 'ir' THEN 'Southern Asia'
        WHEN 'iq' THEN 'Western Asia'
        WHEN 'ie' THEN 'Northern Europe'
        WHEN 'im' THEN 'Northern Europe'
        WHEN 'il' THEN 'Western Asia'
        WHEN 'it' THEN 'Southern Europe'
        WHEN 'jm' THEN 'Latin America and the Caribbean'
        WHEN 'jp' THEN 'Eastern Asia'
        WHEN 'je' THEN 'Northern Europe'
        WHEN 'jo' THEN 'Western Asia'
        WHEN 'kz' THEN 'Central Asia'
        WHEN 'ke' THEN 'Sub-Saharan Africa'
        WHEN 'ki' THEN 'Micronesia'
        WHEN 'kp' THEN 'Eastern Asia'
        WHEN 'kr' THEN 'Eastern Asia'
        WHEN 'kw' THEN 'Western Asia'
        WHEN 'kg' THEN 'Central Asia'
        WHEN 'la' THEN 'South-eastern Asia'
        WHEN 'lv' THEN 'Northern Europe'
        WHEN 'lb' THEN 'Western Asia'
        WHEN 'ls' THEN 'Sub-Saharan Africa'
        WHEN 'lr' THEN 'Sub-Saharan Africa'
        WHEN 'ly' THEN 'Northern Africa'
        WHEN 'li' THEN 'Western Europe'
        WHEN 'lt' THEN 'Northern Europe'
        WHEN 'lu' THEN 'Western Europe'
        WHEN 'mo' THEN 'Eastern Asia'
        WHEN 'mg' THEN 'Sub-Saharan Africa'
        WHEN 'mw' THEN 'Sub-Saharan Africa'
        WHEN 'my' THEN 'South-eastern Asia'
        WHEN 'mv' THEN 'Southern Asia'
        WHEN 'ml' THEN 'Sub-Saharan Africa'
        WHEN 'mt' THEN 'Southern Europe'
        WHEN 'mh' THEN 'Micronesia'
        WHEN 'mq' THEN 'Latin America and the Caribbean'
        WHEN 'mr' THEN 'Sub-Saharan Africa'
        WHEN 'mu' THEN 'Sub-Saharan Africa'
        WHEN 'yt' THEN 'Sub-Saharan Africa'
        WHEN 'mx' THEN 'Latin America and the Caribbean'
        WHEN 'fm' THEN 'Micronesia'
        WHEN 'md' THEN 'Eastern Europe'
        WHEN 'mc' THEN 'Western Europe'
        WHEN 'mn' THEN 'Eastern Asia'
        WHEN 'me' THEN 'Southern Europe'
        WHEN 'ms' THEN 'Latin America and the Caribbean'
        WHEN 'ma' THEN 'Northern Africa'
        WHEN 'mz' THEN 'Sub-Saharan Africa'
        WHEN 'mm' THEN 'South-eastern Asia'
        WHEN 'na' THEN 'Sub-Saharan Africa'
        WHEN 'nr' THEN 'Micronesia'
        WHEN 'np' THEN 'Southern Asia'
        WHEN 'nl' THEN 'Western Europe'
        WHEN 'nc' THEN 'Melanesia'
        WHEN 'nz' THEN 'Australia and New Zealand'
        WHEN 'ni' THEN 'Latin America and the Caribbean'
        WHEN 'ne' THEN 'Sub-Saharan Africa'
        WHEN 'ng' THEN 'Sub-Saharan Africa'
        WHEN 'nu' THEN 'Polynesia'
        WHEN 'nf' THEN 'Australia and New Zealand'
        WHEN 'mk' THEN 'Southern Europe'
        WHEN 'mp' THEN 'Micronesia'
        WHEN 'no' THEN 'Northern Europe'
        WHEN 'om' THEN 'Western Asia'
        WHEN 'pk' THEN 'Southern Asia'
        WHEN 'pw' THEN 'Micronesia'
        WHEN 'ps' THEN 'Western Asia'
        WHEN 'pa' THEN 'Latin America and the Caribbean'
        WHEN 'pg' THEN 'Melanesia'
        WHEN 'py' THEN 'Latin America and the Caribbean'
        WHEN 'pe' THEN 'Latin America and the Caribbean'
        WHEN 'ph' THEN 'South-eastern Asia'
        WHEN 'pn' THEN 'Polynesia'
        WHEN 'pl' THEN 'Eastern Europe'
        WHEN 'pt' THEN 'Southern Europe'
        WHEN 'pr' THEN 'Latin America and the Caribbean'
        WHEN 'qa' THEN 'Western Asia'
        WHEN 're' THEN 'Sub-Saharan Africa'
        WHEN 'ro' THEN 'Eastern Europe'
        WHEN 'ru' THEN 'Eastern Europe'
        WHEN 'rw' THEN 'Sub-Saharan Africa'
        WHEN 'bl' THEN 'Latin America and the Caribbean'
        WHEN 'sh' THEN 'Sub-Saharan Africa'
        WHEN 'kn' THEN 'Latin America and the Caribbean'
        WHEN 'lc' THEN 'Latin America and the Caribbean'
        WHEN 'mf' THEN 'Latin America and the Caribbean'
        WHEN 'pm' THEN 'Northern America'
        WHEN 'vc' THEN 'Latin America and the Caribbean'
        WHEN 'ws' THEN 'Polynesia'
        WHEN 'sm' THEN 'Southern Europe'
        WHEN 'st' THEN 'Sub-Saharan Africa'
        WHEN 'sa' THEN 'Western Asia'
        WHEN 'sn' THEN 'Sub-Saharan Africa'
        WHEN 'rs' THEN 'Southern Europe'
        WHEN 'sc' THEN 'Sub-Saharan Africa'
        WHEN 'sl' THEN 'Sub-Saharan Africa'
        WHEN 'sg' THEN 'South-eastern Asia'
        WHEN 'sx' THEN 'Latin America and the Caribbean'
        WHEN 'sk' THEN 'Eastern Europe'
        WHEN 'si' THEN 'Southern Europe'
        WHEN 'sb' THEN 'Melanesia'
        WHEN 'so' THEN 'Sub-Saharan Africa'
        WHEN 'za' THEN 'Sub-Saharan Africa'
        WHEN 'gs' THEN 'Latin America and the Caribbean'
        WHEN 'ss' THEN 'Sub-Saharan Africa'
        WHEN 'es' THEN 'Southern Europe'
        WHEN 'lk' THEN 'Southern Asia'
        WHEN 'sd' THEN 'Northern Africa'
        WHEN 'sr' THEN 'Latin America and the Caribbean'
        WHEN 'sj' THEN 'Northern Europe'
        WHEN 'se' THEN 'Northern Europe'
        WHEN 'ch' THEN 'Western Europe'
        WHEN 'sy' THEN 'Western Asia'
        WHEN 'tw' THEN 'Unknown'
        WHEN 'tj' THEN 'Central Asia'
        WHEN 'tz' THEN 'Sub-Saharan Africa'
        WHEN 'th' THEN 'South-eastern Asia'
        WHEN 'tl' THEN 'South-eastern Asia'
        WHEN 'tg' THEN 'Sub-Saharan Africa'
        WHEN 'tk' THEN 'Polynesia'
        WHEN 'to' THEN 'Polynesia'
        WHEN 'tt' THEN 'Latin America and the Caribbean'
        WHEN 'tn' THEN 'Northern Africa'
        WHEN 'tr' THEN 'Western Asia'
        WHEN 'tm' THEN 'Central Asia'
        WHEN 'tc' THEN 'Latin America and the Caribbean'
        WHEN 'tv' THEN 'Polynesia'
        WHEN 'ug' THEN 'Sub-Saharan Africa'
        WHEN 'ua' THEN 'Eastern Europe'
        WHEN 'ae' THEN 'Western Asia'
        WHEN 'gb' THEN 'Northern Europe'
        WHEN 'us' THEN 'Northern America'
        WHEN 'um' THEN 'Micronesia'
        WHEN 'uy' THEN 'Latin America and the Caribbean'
        WHEN 'uz' THEN 'Central Asia'
        WHEN 'vu' THEN 'Melanesia'
        WHEN 've' THEN 'Latin America and the Caribbean'
        WHEN 'vn' THEN 'South-eastern Asia'
        WHEN 'vg' THEN 'Latin America and the Caribbean'
        WHEN 'vi' THEN 'Latin America and the Caribbean'
        WHEN 'wf' THEN 'Polynesia'
        WHEN 'eh' THEN 'Northern Africa'
        WHEN 'ye' THEN 'Western Asia'
        WHEN 'zm' THEN 'Sub-Saharan Africa'
        WHEN 'zw' THEN 'Sub-Saharan Africa'
        ELSE 'Unknown'
    END;
