UPDATE speakers
SET
    "Region" = CASE LOWER(TRIM(country))
        WHEN 'afghanistan' THEN 'Asia'
        WHEN 'aland islands' THEN 'Europe'
        WHEN 'albania' THEN 'Europe'
        WHEN 'algeria' THEN 'Africa'
        WHEN 'american samoa' THEN 'Oceania'
        WHEN 'andorra' THEN 'Europe'
        WHEN 'angola' THEN 'Africa'
        WHEN 'anguilla' THEN 'Americas'
        WHEN 'antarctica' THEN 'Unknown'
        WHEN 'antigua and barbuda' THEN 'Americas'
        WHEN 'argentina' THEN 'Americas'
        WHEN 'armenia' THEN 'Asia'
        WHEN 'aruba' THEN 'Americas'
        WHEN 'australia' THEN 'Oceania'
        WHEN 'austria' THEN 'Europe'
        WHEN 'azerbaijan' THEN 'Asia'
        WHEN 'bahamas' THEN 'Americas'
        WHEN 'bahrain' THEN 'Asia'
        WHEN 'bangladesh' THEN 'Asia'
        WHEN 'barbados' THEN 'Americas'
        WHEN 'belarus' THEN 'Europe'
        WHEN 'belgium' THEN 'Europe'
        WHEN 'belize' THEN 'Americas'
        WHEN 'benin' THEN 'Africa'
        WHEN 'bermuda' THEN 'Americas'
        WHEN 'bhutan' THEN 'Asia'
        WHEN 'bolivia' THEN 'Americas'
        WHEN 'bolivia, plurinational state of' THEN 'Americas'
        WHEN 'bonaire, sint eustatius and saba' THEN 'Americas'
        WHEN 'bosnia and herzegovina' THEN 'Europe'
        WHEN 'botswana' THEN 'Africa'
        WHEN 'bouvet island' THEN 'Americas'
        WHEN 'brazil' THEN 'Americas'
        WHEN 'britain' THEN 'Europe'
        WHEN 'british indian ocean territory' THEN 'Africa'
        WHEN 'brunei' THEN 'Asia'
        WHEN 'brunei darussalam' THEN 'Asia'
        WHEN 'bulgaria' THEN 'Europe'
        WHEN 'burkina faso' THEN 'Africa'
        WHEN 'burma' THEN 'Asia'
        WHEN 'burundi' THEN 'Africa'
        WHEN 'cabo verde' THEN 'Africa'
        WHEN 'cambodia' THEN 'Asia'
        WHEN 'cameroon' THEN 'Africa'
        WHEN 'canada' THEN 'Americas'
        WHEN 'cape verde' THEN 'Africa'
        WHEN 'cayman islands' THEN 'Americas'
        WHEN 'central african republic' THEN 'Africa'
        WHEN 'chad' THEN 'Africa'
        WHEN 'chile' THEN 'Americas'
        WHEN 'china' THEN 'Asia'
        WHEN 'christmas island' THEN 'Oceania'
        WHEN 'cocos (keeling) islands' THEN 'Oceania'
        WHEN 'colombia' THEN 'Americas'
        WHEN 'comoros' THEN 'Africa'
        WHEN 'congo' THEN 'Africa'
        WHEN 'congo, democratic republic of the' THEN 'Africa'
        WHEN 'cook islands' THEN 'Oceania'
        WHEN 'costa rica' THEN 'Americas'
        WHEN 'cote d''ivoire' THEN 'Africa'
        WHEN 'croatia' THEN 'Europe'
        WHEN 'cuba' THEN 'Americas'
        WHEN 'curacao' THEN 'Americas'
        WHEN 'cyprus' THEN 'Asia'
        WHEN 'czech republic' THEN 'Europe'
        WHEN 'czechia' THEN 'Europe'
        WHEN 'denmark' THEN 'Europe'
        WHEN 'djibouti' THEN 'Africa'
        WHEN 'dominica' THEN 'Americas'
        WHEN 'dominican republic' THEN 'Americas'
        WHEN 'ecuador' THEN 'Americas'
        WHEN 'egypt' THEN 'Africa'
        WHEN 'el salvador' THEN 'Americas'
        WHEN 'equatorial guinea' THEN 'Africa'
        WHEN 'eritrea' THEN 'Africa'
        WHEN 'estonia' THEN 'Europe'
        WHEN 'eswatini' THEN 'Africa'
        WHEN 'ethiopia' THEN 'Africa'
        WHEN 'falkland islands (malvinas)' THEN 'Americas'
        WHEN 'faroe islands' THEN 'Europe'
        WHEN 'fiji' THEN 'Oceania'
        WHEN 'finland' THEN 'Europe'
        WHEN 'france' THEN 'Europe'
        WHEN 'french guiana' THEN 'Americas'
        WHEN 'french polynesia' THEN 'Oceania'
        WHEN 'french southern territories' THEN 'Africa'
        WHEN 'gabon' THEN 'Africa'
        WHEN 'gambia' THEN 'Africa'
        WHEN 'georgia' THEN 'Asia'
        WHEN 'germany' THEN 'Europe'
        WHEN 'ghana' THEN 'Africa'
        WHEN 'gibraltar' THEN 'Europe'
        WHEN 'great britain' THEN 'Europe'
        WHEN 'greece' THEN 'Europe'
        WHEN 'greenland' THEN 'Americas'
        WHEN 'grenada' THEN 'Americas'
        WHEN 'guadeloupe' THEN 'Americas'
        WHEN 'guam' THEN 'Oceania'
        WHEN 'guatemala' THEN 'Americas'
        WHEN 'guernsey' THEN 'Europe'
        WHEN 'guinea' THEN 'Africa'
        WHEN 'guinea-bissau' THEN 'Africa'
        WHEN 'guyana' THEN 'Americas'
        WHEN 'haiti' THEN 'Americas'
        WHEN 'heard island and mcdonald islands' THEN 'Oceania'
        WHEN 'holy see' THEN 'Europe'
        WHEN 'honduras' THEN 'Americas'
        WHEN 'hong kong' THEN 'Asia'
        WHEN 'hong kong sar' THEN 'Asia'
        WHEN 'hungary' THEN 'Europe'
        WHEN 'iceland' THEN 'Europe'
        WHEN 'india' THEN 'Asia'
        WHEN 'indonesia' THEN 'Asia'
        WHEN 'iran' THEN 'Asia'
        WHEN 'iran, islamic republic of' THEN 'Asia'
        WHEN 'iraq' THEN 'Asia'
        WHEN 'ireland' THEN 'Europe'
        WHEN 'isle of man' THEN 'Europe'
        WHEN 'israel' THEN 'Asia'
        WHEN 'italy' THEN 'Europe'
        WHEN 'ivory coast' THEN 'Africa'
        WHEN 'jamaica' THEN 'Americas'
        WHEN 'japan' THEN 'Asia'
        WHEN 'jersey' THEN 'Europe'
        WHEN 'jordan' THEN 'Asia'
        WHEN 'kazakhstan' THEN 'Asia'
        WHEN 'kenya' THEN 'Africa'
        WHEN 'kiribati' THEN 'Oceania'
        WHEN 'korea' THEN 'Asia'
        WHEN 'korea, democratic people''s republic of' THEN 'Asia'
        WHEN 'korea, republic of' THEN 'Asia'
        WHEN 'kuwait' THEN 'Asia'
        WHEN 'kyrgyzstan' THEN 'Asia'
        WHEN 'lao people''s democratic republic' THEN 'Asia'
        WHEN 'laos' THEN 'Asia'
        WHEN 'latvia' THEN 'Europe'
        WHEN 'lebanon' THEN 'Asia'
        WHEN 'lesotho' THEN 'Africa'
        WHEN 'liberia' THEN 'Africa'
        WHEN 'libya' THEN 'Africa'
        WHEN 'liechtenstein' THEN 'Europe'
        WHEN 'lithuania' THEN 'Europe'
        WHEN 'luxembourg' THEN 'Europe'
        WHEN 'macao' THEN 'Asia'
        WHEN 'macau' THEN 'Asia'
        WHEN 'macedonia' THEN 'Europe'
        WHEN 'madagascar' THEN 'Africa'
        WHEN 'malawi' THEN 'Africa'
        WHEN 'malaysia' THEN 'Asia'
        WHEN 'maldives' THEN 'Asia'
        WHEN 'mali' THEN 'Africa'
        WHEN 'malta' THEN 'Europe'
        WHEN 'marshall islands' THEN 'Oceania'
        WHEN 'martinique' THEN 'Americas'
        WHEN 'mauritania' THEN 'Africa'
        WHEN 'mauritius' THEN 'Africa'
        WHEN 'mayotte' THEN 'Africa'
        WHEN 'mexico' THEN 'Americas'
        WHEN 'micronesia' THEN 'Oceania'
        WHEN 'micronesia, federated states of' THEN 'Oceania'
        WHEN 'moldova' THEN 'Europe'
        WHEN 'moldova, republic of' THEN 'Europe'
        WHEN 'monaco' THEN 'Europe'
        WHEN 'mongolia' THEN 'Asia'
        WHEN 'montenegro' THEN 'Europe'
        WHEN 'montserrat' THEN 'Americas'
        WHEN 'morocco' THEN 'Africa'
        WHEN 'mozambique' THEN 'Africa'
        WHEN 'myanmar' THEN 'Asia'
        WHEN 'namibia' THEN 'Africa'
        WHEN 'nauru' THEN 'Oceania'
        WHEN 'nepal' THEN 'Asia'
        WHEN 'netherlands' THEN 'Europe'
        WHEN 'netherlands, kingdom of the' THEN 'Europe'
        WHEN 'new caledonia' THEN 'Oceania'
        WHEN 'new zealand' THEN 'Oceania'
        WHEN 'nicaragua' THEN 'Americas'
        WHEN 'niger' THEN 'Africa'
        WHEN 'nigeria' THEN 'Africa'
        WHEN 'niue' THEN 'Oceania'
        WHEN 'norfolk island' THEN 'Oceania'
        WHEN 'north korea' THEN 'Asia'
        WHEN 'north macedonia' THEN 'Europe'
        WHEN 'northern mariana islands' THEN 'Oceania'
        WHEN 'norway' THEN 'Europe'
        WHEN 'oman' THEN 'Asia'
        WHEN 'pakistan' THEN 'Asia'
        WHEN 'palau' THEN 'Oceania'
        WHEN 'palestine' THEN 'Asia'
        WHEN 'palestine, state of' THEN 'Asia'
        WHEN 'panama' THEN 'Americas'
        WHEN 'papua new guinea' THEN 'Oceania'
        WHEN 'paraguay' THEN 'Americas'
        WHEN 'peru' THEN 'Americas'
        WHEN 'philippines' THEN 'Asia'
        WHEN 'pitcairn' THEN 'Oceania'
        WHEN 'poland' THEN 'Europe'
        WHEN 'portugal' THEN 'Europe'
        WHEN 'puerto rico' THEN 'Americas'
        WHEN 'qatar' THEN 'Asia'
        WHEN 'reunion' THEN 'Africa'
        WHEN 'romania' THEN 'Europe'
        WHEN 'russia' THEN 'Europe'
        WHEN 'russian federation' THEN 'Europe'
        WHEN 'rwanda' THEN 'Africa'
        WHEN 'saint barthelemy' THEN 'Americas'
        WHEN 'saint helena, ascension and tristan da cunha' THEN 'Africa'
        WHEN 'saint kitts and nevis' THEN 'Americas'
        WHEN 'saint lucia' THEN 'Americas'
        WHEN 'saint martin (french part)' THEN 'Americas'
        WHEN 'saint pierre and miquelon' THEN 'Americas'
        WHEN 'saint vincent and the grenadines' THEN 'Americas'
        WHEN 'samoa' THEN 'Oceania'
        WHEN 'san marino' THEN 'Europe'
        WHEN 'sao tome and principe' THEN 'Africa'
        WHEN 'saudi arabia' THEN 'Asia'
        WHEN 'senegal' THEN 'Africa'
        WHEN 'serbia' THEN 'Europe'
        WHEN 'seychelles' THEN 'Africa'
        WHEN 'sierra leone' THEN 'Africa'
        WHEN 'singapore' THEN 'Asia'
        WHEN 'sint maarten (dutch part)' THEN 'Americas'
        WHEN 'slovakia' THEN 'Europe'
        WHEN 'slovenia' THEN 'Europe'
        WHEN 'solomon islands' THEN 'Oceania'
        WHEN 'somalia' THEN 'Africa'
        WHEN 'south africa' THEN 'Africa'
        WHEN 'south georgia and the south sandwich islands' THEN 'Americas'
        WHEN 'south korea' THEN 'Asia'
        WHEN 'south sudan' THEN 'Africa'
        WHEN 'spain' THEN 'Europe'
        WHEN 'sri lanka' THEN 'Asia'
        WHEN 'sudan' THEN 'Africa'
        WHEN 'suriname' THEN 'Americas'
        WHEN 'svalbard and jan mayen' THEN 'Europe'
        WHEN 'swaziland' THEN 'Africa'
        WHEN 'sweden' THEN 'Europe'
        WHEN 'switzerland' THEN 'Europe'
        WHEN 'syria' THEN 'Asia'
        WHEN 'syrian arab republic' THEN 'Asia'
        WHEN 'taiwan, province of china' THEN 'Unknown'
        WHEN 'tajikistan' THEN 'Asia'
        WHEN 'tanzania' THEN 'Africa'
        WHEN 'tanzania, united republic of' THEN 'Africa'
        WHEN 'thailand' THEN 'Asia'
        WHEN 'timor-leste' THEN 'Asia'
        WHEN 'togo' THEN 'Africa'
        WHEN 'tokelau' THEN 'Oceania'
        WHEN 'tonga' THEN 'Oceania'
        WHEN 'trinidad and tobago' THEN 'Americas'
        WHEN 'tunisia' THEN 'Africa'
        WHEN 'turkey' THEN 'Asia'
        WHEN 'turkiye' THEN 'Asia'
        WHEN 'turkmenistan' THEN 'Asia'
        WHEN 'turks and caicos islands' THEN 'Americas'
        WHEN 'tuvalu' THEN 'Oceania'
        WHEN 'u.s.' THEN 'Americas'
        WHEN 'u.s.a' THEN 'Americas'
        WHEN 'uae' THEN 'Asia'
        WHEN 'uganda' THEN 'Africa'
        WHEN 'uk' THEN 'Europe'
        WHEN 'ukraine' THEN 'Europe'
        WHEN 'united arab emirates' THEN 'Asia'
        WHEN 'united kingdom' THEN 'Europe'
        WHEN 'united kingdom of great britain and northern ireland' THEN 'Europe'
        WHEN 'united states' THEN 'Americas'
        WHEN 'united states minor outlying islands' THEN 'Oceania'
        WHEN 'united states of america' THEN 'Americas'
        WHEN 'uruguay' THEN 'Americas'
        WHEN 'us' THEN 'Americas'
        WHEN 'usa' THEN 'Americas'
        WHEN 'uzbekistan' THEN 'Asia'
        WHEN 'vanuatu' THEN 'Oceania'
        WHEN 'vatican' THEN 'Europe'
        WHEN 'vatican city' THEN 'Europe'
        WHEN 'venezuela' THEN 'Americas'
        WHEN 'venezuela, bolivarian republic of' THEN 'Americas'
        WHEN 'viet nam' THEN 'Asia'
        WHEN 'vietnam' THEN 'Asia'
        WHEN 'virgin islands (british)' THEN 'Americas'
        WHEN 'virgin islands (u.s.)' THEN 'Americas'
        WHEN 'wallis and futuna' THEN 'Oceania'
        WHEN 'western sahara' THEN 'Africa'
        WHEN 'yemen' THEN 'Asia'
        WHEN 'zambia' THEN 'Africa'
        WHEN 'zimbabwe' THEN 'Africa'
        WHEN 'the netherlands' THEN 'Europe'
        WHEN 'the philippines' THEN 'Asia'
        WHEN 'türkiye' THEN 'Asia'
        WHEN 'turkiye' THEN 'Asia'
        ELSE 'Unknown'
    END,
    "SubRegion" = CASE LOWER(TRIM(country))
        WHEN 'afghanistan' THEN 'Southern Asia'
        WHEN 'aland islands' THEN 'Northern Europe'
        WHEN 'albania' THEN 'Southern Europe'
        WHEN 'algeria' THEN 'Northern Africa'
        WHEN 'american samoa' THEN 'Polynesia'
        WHEN 'andorra' THEN 'Southern Europe'
        WHEN 'angola' THEN 'Sub-Saharan Africa'
        WHEN 'anguilla' THEN 'Latin America and the Caribbean'
        WHEN 'antarctica' THEN 'Unknown'
        WHEN 'antigua and barbuda' THEN 'Latin America and the Caribbean'
        WHEN 'argentina' THEN 'Latin America and the Caribbean'
        WHEN 'armenia' THEN 'Western Asia'
        WHEN 'aruba' THEN 'Latin America and the Caribbean'
        WHEN 'australia' THEN 'Australia and New Zealand'
        WHEN 'austria' THEN 'Western Europe'
        WHEN 'azerbaijan' THEN 'Western Asia'
        WHEN 'bahamas' THEN 'Latin America and the Caribbean'
        WHEN 'bahrain' THEN 'Western Asia'
        WHEN 'bangladesh' THEN 'Southern Asia'
        WHEN 'barbados' THEN 'Latin America and the Caribbean'
        WHEN 'belarus' THEN 'Eastern Europe'
        WHEN 'belgium' THEN 'Western Europe'
        WHEN 'belize' THEN 'Latin America and the Caribbean'
        WHEN 'benin' THEN 'Sub-Saharan Africa'
        WHEN 'bermuda' THEN 'Northern America'
        WHEN 'bhutan' THEN 'Southern Asia'
        WHEN 'bolivia' THEN 'Latin America and the Caribbean'
        WHEN 'bolivia, plurinational state of' THEN 'Latin America and the Caribbean'
        WHEN 'bonaire, sint eustatius and saba' THEN 'Latin America and the Caribbean'
        WHEN 'bosnia and herzegovina' THEN 'Southern Europe'
        WHEN 'botswana' THEN 'Sub-Saharan Africa'
        WHEN 'bouvet island' THEN 'Latin America and the Caribbean'
        WHEN 'brazil' THEN 'Latin America and the Caribbean'
        WHEN 'britain' THEN 'Northern Europe'
        WHEN 'british indian ocean territory' THEN 'Sub-Saharan Africa'
        WHEN 'brunei' THEN 'South-eastern Asia'
        WHEN 'brunei darussalam' THEN 'South-eastern Asia'
        WHEN 'bulgaria' THEN 'Eastern Europe'
        WHEN 'burkina faso' THEN 'Sub-Saharan Africa'
        WHEN 'burma' THEN 'South-eastern Asia'
        WHEN 'burundi' THEN 'Sub-Saharan Africa'
        WHEN 'cabo verde' THEN 'Sub-Saharan Africa'
        WHEN 'cambodia' THEN 'South-eastern Asia'
        WHEN 'cameroon' THEN 'Sub-Saharan Africa'
        WHEN 'canada' THEN 'Northern America'
        WHEN 'cape verde' THEN 'Sub-Saharan Africa'
        WHEN 'cayman islands' THEN 'Latin America and the Caribbean'
        WHEN 'central african republic' THEN 'Sub-Saharan Africa'
        WHEN 'chad' THEN 'Sub-Saharan Africa'
        WHEN 'chile' THEN 'Latin America and the Caribbean'
        WHEN 'china' THEN 'Eastern Asia'
        WHEN 'christmas island' THEN 'Australia and New Zealand'
        WHEN 'cocos (keeling) islands' THEN 'Australia and New Zealand'
        WHEN 'colombia' THEN 'Latin America and the Caribbean'
        WHEN 'comoros' THEN 'Sub-Saharan Africa'
        WHEN 'congo' THEN 'Sub-Saharan Africa'
        WHEN 'congo, democratic republic of the' THEN 'Sub-Saharan Africa'
        WHEN 'cook islands' THEN 'Polynesia'
        WHEN 'costa rica' THEN 'Latin America and the Caribbean'
        WHEN 'cote d''ivoire' THEN 'Sub-Saharan Africa'
        WHEN 'croatia' THEN 'Southern Europe'
        WHEN 'cuba' THEN 'Latin America and the Caribbean'
        WHEN 'curacao' THEN 'Latin America and the Caribbean'
        WHEN 'cyprus' THEN 'Western Asia'
        WHEN 'czech republic' THEN 'Eastern Europe'
        WHEN 'czechia' THEN 'Eastern Europe'
        WHEN 'denmark' THEN 'Northern Europe'
        WHEN 'djibouti' THEN 'Sub-Saharan Africa'
        WHEN 'dominica' THEN 'Latin America and the Caribbean'
        WHEN 'dominican republic' THEN 'Latin America and the Caribbean'
        WHEN 'ecuador' THEN 'Latin America and the Caribbean'
        WHEN 'egypt' THEN 'Northern Africa'
        WHEN 'el salvador' THEN 'Latin America and the Caribbean'
        WHEN 'equatorial guinea' THEN 'Sub-Saharan Africa'
        WHEN 'eritrea' THEN 'Sub-Saharan Africa'
        WHEN 'estonia' THEN 'Northern Europe'
        WHEN 'eswatini' THEN 'Sub-Saharan Africa'
        WHEN 'ethiopia' THEN 'Sub-Saharan Africa'
        WHEN 'falkland islands (malvinas)' THEN 'Latin America and the Caribbean'
        WHEN 'faroe islands' THEN 'Northern Europe'
        WHEN 'fiji' THEN 'Melanesia'
        WHEN 'finland' THEN 'Northern Europe'
        WHEN 'france' THEN 'Western Europe'
        WHEN 'french guiana' THEN 'Latin America and the Caribbean'
        WHEN 'french polynesia' THEN 'Polynesia'
        WHEN 'french southern territories' THEN 'Sub-Saharan Africa'
        WHEN 'gabon' THEN 'Sub-Saharan Africa'
        WHEN 'gambia' THEN 'Sub-Saharan Africa'
        WHEN 'georgia' THEN 'Western Asia'
        WHEN 'germany' THEN 'Western Europe'
        WHEN 'ghana' THEN 'Sub-Saharan Africa'
        WHEN 'gibraltar' THEN 'Southern Europe'
        WHEN 'great britain' THEN 'Northern Europe'
        WHEN 'greece' THEN 'Southern Europe'
        WHEN 'greenland' THEN 'Northern America'
        WHEN 'grenada' THEN 'Latin America and the Caribbean'
        WHEN 'guadeloupe' THEN 'Latin America and the Caribbean'
        WHEN 'guam' THEN 'Micronesia'
        WHEN 'guatemala' THEN 'Latin America and the Caribbean'
        WHEN 'guernsey' THEN 'Northern Europe'
        WHEN 'guinea' THEN 'Sub-Saharan Africa'
        WHEN 'guinea-bissau' THEN 'Sub-Saharan Africa'
        WHEN 'guyana' THEN 'Latin America and the Caribbean'
        WHEN 'haiti' THEN 'Latin America and the Caribbean'
        WHEN 'heard island and mcdonald islands' THEN 'Australia and New Zealand'
        WHEN 'holy see' THEN 'Southern Europe'
        WHEN 'honduras' THEN 'Latin America and the Caribbean'
        WHEN 'hong kong' THEN 'Eastern Asia'
        WHEN 'hong kong sar' THEN 'Eastern Asia'
        WHEN 'hungary' THEN 'Eastern Europe'
        WHEN 'iceland' THEN 'Northern Europe'
        WHEN 'india' THEN 'Southern Asia'
        WHEN 'indonesia' THEN 'South-eastern Asia'
        WHEN 'iran' THEN 'Southern Asia'
        WHEN 'iran, islamic republic of' THEN 'Southern Asia'
        WHEN 'iraq' THEN 'Western Asia'
        WHEN 'ireland' THEN 'Northern Europe'
        WHEN 'isle of man' THEN 'Northern Europe'
        WHEN 'israel' THEN 'Western Asia'
        WHEN 'italy' THEN 'Southern Europe'
        WHEN 'ivory coast' THEN 'Sub-Saharan Africa'
        WHEN 'jamaica' THEN 'Latin America and the Caribbean'
        WHEN 'japan' THEN 'Eastern Asia'
        WHEN 'jersey' THEN 'Northern Europe'
        WHEN 'jordan' THEN 'Western Asia'
        WHEN 'kazakhstan' THEN 'Central Asia'
        WHEN 'kenya' THEN 'Sub-Saharan Africa'
        WHEN 'kiribati' THEN 'Micronesia'
        WHEN 'korea' THEN 'Eastern Asia'
        WHEN 'korea, democratic people''s republic of' THEN 'Eastern Asia'
        WHEN 'korea, republic of' THEN 'Eastern Asia'
        WHEN 'kuwait' THEN 'Western Asia'
        WHEN 'kyrgyzstan' THEN 'Central Asia'
        WHEN 'lao people''s democratic republic' THEN 'South-eastern Asia'
        WHEN 'laos' THEN 'South-eastern Asia'
        WHEN 'latvia' THEN 'Northern Europe'
        WHEN 'lebanon' THEN 'Western Asia'
        WHEN 'lesotho' THEN 'Sub-Saharan Africa'
        WHEN 'liberia' THEN 'Sub-Saharan Africa'
        WHEN 'libya' THEN 'Northern Africa'
        WHEN 'liechtenstein' THEN 'Western Europe'
        WHEN 'lithuania' THEN 'Northern Europe'
        WHEN 'luxembourg' THEN 'Western Europe'
        WHEN 'macao' THEN 'Eastern Asia'
        WHEN 'macau' THEN 'Eastern Asia'
        WHEN 'macedonia' THEN 'Southern Europe'
        WHEN 'madagascar' THEN 'Sub-Saharan Africa'
        WHEN 'malawi' THEN 'Sub-Saharan Africa'
        WHEN 'malaysia' THEN 'South-eastern Asia'
        WHEN 'maldives' THEN 'Southern Asia'
        WHEN 'mali' THEN 'Sub-Saharan Africa'
        WHEN 'malta' THEN 'Southern Europe'
        WHEN 'marshall islands' THEN 'Micronesia'
        WHEN 'martinique' THEN 'Latin America and the Caribbean'
        WHEN 'mauritania' THEN 'Sub-Saharan Africa'
        WHEN 'mauritius' THEN 'Sub-Saharan Africa'
        WHEN 'mayotte' THEN 'Sub-Saharan Africa'
        WHEN 'mexico' THEN 'Latin America and the Caribbean'
        WHEN 'micronesia' THEN 'Micronesia'
        WHEN 'micronesia, federated states of' THEN 'Micronesia'
        WHEN 'moldova' THEN 'Eastern Europe'
        WHEN 'moldova, republic of' THEN 'Eastern Europe'
        WHEN 'monaco' THEN 'Western Europe'
        WHEN 'mongolia' THEN 'Eastern Asia'
        WHEN 'montenegro' THEN 'Southern Europe'
        WHEN 'montserrat' THEN 'Latin America and the Caribbean'
        WHEN 'morocco' THEN 'Northern Africa'
        WHEN 'mozambique' THEN 'Sub-Saharan Africa'
        WHEN 'myanmar' THEN 'South-eastern Asia'
        WHEN 'namibia' THEN 'Sub-Saharan Africa'
        WHEN 'nauru' THEN 'Micronesia'
        WHEN 'nepal' THEN 'Southern Asia'
        WHEN 'netherlands' THEN 'Western Europe'
        WHEN 'netherlands, kingdom of the' THEN 'Western Europe'
        WHEN 'new caledonia' THEN 'Melanesia'
        WHEN 'new zealand' THEN 'Australia and New Zealand'
        WHEN 'nicaragua' THEN 'Latin America and the Caribbean'
        WHEN 'niger' THEN 'Sub-Saharan Africa'
        WHEN 'nigeria' THEN 'Sub-Saharan Africa'
        WHEN 'niue' THEN 'Polynesia'
        WHEN 'norfolk island' THEN 'Australia and New Zealand'
        WHEN 'north korea' THEN 'Eastern Asia'
        WHEN 'north macedonia' THEN 'Southern Europe'
        WHEN 'northern mariana islands' THEN 'Micronesia'
        WHEN 'norway' THEN 'Northern Europe'
        WHEN 'oman' THEN 'Western Asia'
        WHEN 'pakistan' THEN 'Southern Asia'
        WHEN 'palau' THEN 'Micronesia'
        WHEN 'palestine' THEN 'Western Asia'
        WHEN 'palestine, state of' THEN 'Western Asia'
        WHEN 'panama' THEN 'Latin America and the Caribbean'
        WHEN 'papua new guinea' THEN 'Melanesia'
        WHEN 'paraguay' THEN 'Latin America and the Caribbean'
        WHEN 'peru' THEN 'Latin America and the Caribbean'
        WHEN 'philippines' THEN 'South-eastern Asia'
        WHEN 'pitcairn' THEN 'Polynesia'
        WHEN 'poland' THEN 'Eastern Europe'
        WHEN 'portugal' THEN 'Southern Europe'
        WHEN 'puerto rico' THEN 'Latin America and the Caribbean'
        WHEN 'qatar' THEN 'Western Asia'
        WHEN 'reunion' THEN 'Sub-Saharan Africa'
        WHEN 'romania' THEN 'Eastern Europe'
        WHEN 'russia' THEN 'Eastern Europe'
        WHEN 'russian federation' THEN 'Eastern Europe'
        WHEN 'rwanda' THEN 'Sub-Saharan Africa'
        WHEN 'saint barthelemy' THEN 'Latin America and the Caribbean'
        WHEN 'saint helena, ascension and tristan da cunha' THEN 'Sub-Saharan Africa'
        WHEN 'saint kitts and nevis' THEN 'Latin America and the Caribbean'
        WHEN 'saint lucia' THEN 'Latin America and the Caribbean'
        WHEN 'saint martin (french part)' THEN 'Latin America and the Caribbean'
        WHEN 'saint pierre and miquelon' THEN 'Northern America'
        WHEN 'saint vincent and the grenadines' THEN 'Latin America and the Caribbean'
        WHEN 'samoa' THEN 'Polynesia'
        WHEN 'san marino' THEN 'Southern Europe'
        WHEN 'sao tome and principe' THEN 'Sub-Saharan Africa'
        WHEN 'saudi arabia' THEN 'Western Asia'
        WHEN 'senegal' THEN 'Sub-Saharan Africa'
        WHEN 'serbia' THEN 'Southern Europe'
        WHEN 'seychelles' THEN 'Sub-Saharan Africa'
        WHEN 'sierra leone' THEN 'Sub-Saharan Africa'
        WHEN 'singapore' THEN 'South-eastern Asia'
        WHEN 'sint maarten (dutch part)' THEN 'Latin America and the Caribbean'
        WHEN 'slovakia' THEN 'Eastern Europe'
        WHEN 'slovenia' THEN 'Southern Europe'
        WHEN 'solomon islands' THEN 'Melanesia'
        WHEN 'somalia' THEN 'Sub-Saharan Africa'
        WHEN 'south africa' THEN 'Sub-Saharan Africa'
        WHEN 'south georgia and the south sandwich islands' THEN 'Latin America and the Caribbean'
        WHEN 'south korea' THEN 'Eastern Asia'
        WHEN 'south sudan' THEN 'Sub-Saharan Africa'
        WHEN 'spain' THEN 'Southern Europe'
        WHEN 'sri lanka' THEN 'Southern Asia'
        WHEN 'sudan' THEN 'Northern Africa'
        WHEN 'suriname' THEN 'Latin America and the Caribbean'
        WHEN 'svalbard and jan mayen' THEN 'Northern Europe'
        WHEN 'swaziland' THEN 'Sub-Saharan Africa'
        WHEN 'sweden' THEN 'Northern Europe'
        WHEN 'switzerland' THEN 'Western Europe'
        WHEN 'syria' THEN 'Western Asia'
        WHEN 'syrian arab republic' THEN 'Western Asia'
        WHEN 'taiwan, province of china' THEN 'Unknown'
        WHEN 'tajikistan' THEN 'Central Asia'
        WHEN 'tanzania' THEN 'Sub-Saharan Africa'
        WHEN 'tanzania, united republic of' THEN 'Sub-Saharan Africa'
        WHEN 'thailand' THEN 'South-eastern Asia'
        WHEN 'timor-leste' THEN 'South-eastern Asia'
        WHEN 'togo' THEN 'Sub-Saharan Africa'
        WHEN 'tokelau' THEN 'Polynesia'
        WHEN 'tonga' THEN 'Polynesia'
        WHEN 'trinidad and tobago' THEN 'Latin America and the Caribbean'
        WHEN 'tunisia' THEN 'Northern Africa'
        WHEN 'turkey' THEN 'Western Asia'
        WHEN 'turkiye' THEN 'Western Asia'
        WHEN 'turkmenistan' THEN 'Central Asia'
        WHEN 'turks and caicos islands' THEN 'Latin America and the Caribbean'
        WHEN 'tuvalu' THEN 'Polynesia'
        WHEN 'u.s.' THEN 'Northern America'
        WHEN 'u.s.a' THEN 'Northern America'
        WHEN 'uae' THEN 'Western Asia'
        WHEN 'uganda' THEN 'Sub-Saharan Africa'
        WHEN 'uk' THEN 'Northern Europe'
        WHEN 'ukraine' THEN 'Eastern Europe'
        WHEN 'united arab emirates' THEN 'Western Asia'
        WHEN 'united kingdom' THEN 'Northern Europe'
        WHEN 'united kingdom of great britain and northern ireland' THEN 'Northern Europe'
        WHEN 'united states' THEN 'Northern America'
        WHEN 'united states minor outlying islands' THEN 'Micronesia'
        WHEN 'united states of america' THEN 'Northern America'
        WHEN 'uruguay' THEN 'Latin America and the Caribbean'
        WHEN 'us' THEN 'Northern America'
        WHEN 'usa' THEN 'Northern America'
        WHEN 'uzbekistan' THEN 'Central Asia'
        WHEN 'vanuatu' THEN 'Melanesia'
        WHEN 'vatican' THEN 'Southern Europe'
        WHEN 'vatican city' THEN 'Southern Europe'
        WHEN 'venezuela' THEN 'Latin America and the Caribbean'
        WHEN 'venezuela, bolivarian republic of' THEN 'Latin America and the Caribbean'
        WHEN 'viet nam' THEN 'South-eastern Asia'
        WHEN 'vietnam' THEN 'South-eastern Asia'
        WHEN 'virgin islands (british)' THEN 'Latin America and the Caribbean'
        WHEN 'virgin islands (u.s.)' THEN 'Latin America and the Caribbean'
        WHEN 'wallis and futuna' THEN 'Polynesia'
        WHEN 'western sahara' THEN 'Northern Africa'
        WHEN 'yemen' THEN 'Western Asia'
        WHEN 'zambia' THEN 'Sub-Saharan Africa'
        WHEN 'zimbabwe' THEN 'Sub-Saharan Africa'
        WHEN 'the netherlands' THEN 'Western Europe'
        WHEN 'the philippines' THEN 'South-eastern Asia'
        WHEN 'türkiye' THEN 'Western Asia'
        WHEN 'turkiye' THEN 'Western Asia'
        ELSE 'Unknown'
    END;
